In [92]:
import numpy as np
import pandas as pd
a = np.array([[1, 2, 3, 3, 1], 
             [6, 8, 11, 10, 7]])

In [93]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [94]:
mean_a = a.mean(axis = 1)

In [95]:
mean_a

array([2. , 8.4])

In [96]:
a_centered = a - mean_a.reshape(len(mean_a), -1)

In [97]:
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [98]:
a_centered_sp = np.dot(a_centered.T, a_centered)

In [99]:
a_centered_sp

array([[ 6.76,  0.96, -7.24, -4.84,  4.36],
       [ 0.96,  0.16, -1.04, -0.64,  0.56],
       [-7.24, -1.04,  7.76,  5.16, -4.64],
       [-4.84, -0.64,  5.16,  3.56, -3.24],
       [ 4.36,  0.56, -4.64, -3.24,  2.96]])

In [100]:
B = a_centered_sp/(a[1] -1)

In [103]:
B

array([[ 1.352     ,  0.13714286, -0.724     , -0.53777778,  0.72666667],
       [ 0.192     ,  0.02285714, -0.104     , -0.07111111,  0.09333333],
       [-1.448     , -0.14857143,  0.776     ,  0.57333333, -0.77333333],
       [-0.968     , -0.09142857,  0.516     ,  0.39555556, -0.54      ],
       [ 0.872     ,  0.08      , -0.464     , -0.36      ,  0.49333333]])

## Pandas

In [105]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [107]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 
'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
'price': [450, 300, 350, 500, 450, 370, 290]
})
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [121]:
authors_price = pd.merge(authors, books, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [122]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [150]:

authors_stat = authors_price.copy()
authors_stat['max'] = authors_price['price'].max()
authors_stat['min'] = authors_price['price'].min()
authors_stat['mean'] = authors_price['price'].mean()

TypeError: 'DataFrameGroupBy' object does not support item assignment

In [148]:
authors_stat.groupby('author_name')
authors_stat

author_id author_name            book_title  price  max  min        mean
0          1    Тургенев           Отцы и дети    450  500  290  387.142857
1          1    Тургенев                 Рудин    300  500  290  387.142857
2          1    Тургенев     Дворянское гнездо    350  500  290  387.142857
3          2       Чехов      Толстый и тонкий    500  500  290  387.142857
4          2       Чехов       Дама с собачкой    450  500  290  387.142857
5          3  Островский                 Гроза    370  500  290  387.142857
6          3  Островский  Таланты и поклонники    290  500  290  387.142857

Object `.agg` not found.
